### ISSUE TITLE
Go 1.4.2 instead of Go 1.5

### ISSUE THREAD

**Issue by pires** [pires/alpine-linux-build#1]
Reported by @bketelsen

**Comment by pires** [comment]
The packages were not upgraded because they're part of `edge`. Bad, bad copy'n'paste engineer!

**Comment by pires** [comment]
```
(...)
(13/15) Installing git (2.5.0-r1)
(14/15) Installing go (1.5-r0)
(15/15) Installing make (4.1-r0)
```

**Comment by drewwells** [comment]
Go 1.5.1-r3 is on edge now. Mind republishing this container?

**Comment by pires** [comment]
@drewwells yeah, but `go` has moved to `community` from `main`. Need to fix first!

**Comment by pires** [comment]
@drewwells see #3 and wait for `20151127` tag to be built on Quay. Thanks for the heads-up!
